name = "PlanetPangaea"
uuid = "e12be0f8-3d1a-49ad-a3b1-1c65e1892401"
authors = ["Greg Munday and contributors"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
